//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('fruits')
export class fruitsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  name: string;

  @Column('text', { nullable: true })
  color: string;

  @Column('integer', { nullable: true })
  points: number;

  @Column('text', { nullable: true })
  specialEffect: string;
}
