//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('levels')
export class levelsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  levelNumber: number;

  @Column('text', { nullable: true })
  difficulty: string;

  @Column('integer', { nullable: true })
  targetScore: number;
}
