//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('players')
export class playersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  playerName: string;

  @Column('integer', { nullable: true })
  currentLevel: number;

  @Column('integer', { nullable: true })
  highScore: number;

  @Column('text', { nullable: true })
  selectedCharacter: string;
}
