//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('scores')
export class scoresEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  playerID: number;

  @Column('integer', { nullable: true })
  scoreValue: number;

  @Column('integer', { nullable: true })
  level: number;
}
