//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const scoresTitle = () => {
  const record = useRecordContext();
  return <span>scores {record ? `"${record.scoreValue}"` : ''}</span>;
};

export const scoresList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="playerID" reference="players" />
      <NumberField source="scoreValue" />
      <ReferenceField source="level" reference="levels" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const scoresEdit = () => (
  <Edit title={<scoresTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="playerID" reference="players" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="scoreValue" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="level" reference="levels" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const scoresCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="playerID" reference="players" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="scoreValue" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="level" reference="levels" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="playerID"
    label="playerID"
    reference="players"
    alwaysOn
  />,
  ,
  <ReferenceInput source="level" label="level" reference="levels" alwaysOn />,
];
