//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Juicy Fruit Match" />
    <CardContent>
      A three-match game featuring juicy fruits instead of candies, with vibrant
      colors, cute characters, and exciting gameplay mechanics.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
