//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    levels: [
      { levelNumber: 1, difficulty: 'difficulty 1', targetScore: 1, id: 35 },
      { levelNumber: 2, difficulty: 'difficulty 2', targetScore: 2, id: 95 },
      { levelNumber: 3, difficulty: 'difficulty 3', targetScore: 3, id: 42 },
      { levelNumber: 4, difficulty: 'difficulty 4', targetScore: 4, id: 98 },
      { levelNumber: 5, difficulty: 'difficulty 5', targetScore: 5, id: 97 },
    ],
    fruits: [
      {
        name: 'name 1',
        color: 'color 1',
        points: 1,
        specialEffect: 'specialEffect 1',
        id: 93,
      },
      {
        name: 'name 2',
        color: 'color 2',
        points: 2,
        specialEffect: 'specialEffect 2',
        id: 18,
      },
      {
        name: 'name 3',
        color: 'color 3',
        points: 3,
        specialEffect: 'specialEffect 3',
        id: 58,
      },
      {
        name: 'name 4',
        color: 'color 4',
        points: 4,
        specialEffect: 'specialEffect 4',
        id: 87,
      },
      {
        name: 'name 5',
        color: 'color 5',
        points: 5,
        specialEffect: 'specialEffect 5',
        id: 34,
      },
    ],
    players: [
      {
        playerName: 'playerName 1',
        currentLevel: 1,
        highScore: 1,
        selectedCharacter: 'selectedCharacter 1',
        id: 44,
      },
      {
        playerName: 'playerName 2',
        currentLevel: 2,
        highScore: 2,
        selectedCharacter: 'selectedCharacter 2',
        id: 43,
      },
      {
        playerName: 'playerName 3',
        currentLevel: 3,
        highScore: 3,
        selectedCharacter: 'selectedCharacter 3',
        id: 48,
      },
      {
        playerName: 'playerName 4',
        currentLevel: 4,
        highScore: 4,
        selectedCharacter: 'selectedCharacter 4',
        id: 18,
      },
      {
        playerName: 'playerName 5',
        currentLevel: 5,
        highScore: 5,
        selectedCharacter: 'selectedCharacter 5',
        id: 35,
      },
    ],
    scores: [
      { playerID: 1, scoreValue: 1, level: 1, id: 73 },
      { playerID: 2, scoreValue: 2, level: 2, id: 4 },
      { playerID: 3, scoreValue: 3, level: 3, id: 17 },
      { playerID: 4, scoreValue: 4, level: 4, id: 13 },
      { playerID: 5, scoreValue: 5, level: 5, id: 59 },
    ],
  },
};
export default data;
